version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - otravo-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - otravo-network
networks:
  cobranza-network:
    name: otravo-network
volumes:
  db:
        
